package com.cloud.paas.appservice.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.Null;
import java.util.Date;

public class SrvVersionDetail extends ValueObject {
    /**
     * 服务版本编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.srv_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    private Integer srvVersionId;

    /**
     * 服务编号
     */
    @Null(message = "{srvVersions.srvId.notNull}", groups = {SrvVersionDetail.SrvVersionAddValidate.class, SrvVersionDetail.SrvVersionUpdateValidate.class})
    private Integer srvId;

    /**
     * 服务版本
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.srv_version
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    @NotBlank(message = "{srvVersions.srvVersion.notBlank}", groups = {SrvVersionDetail.SrvVersionAddValidate.class, SrvVersionDetail.SrvVersionUpdateValidate.class})
    private String srvVersion;

    /**
     * 服务版本描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.srv_version_desc
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    private String srvVersionDesc;

    /**
     * 业务包版本编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.busi_pkg_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    @NotBlank(message = "{srvVersions.busiPkgVersionId.notBlank}", groups = {SrvVersionDetail.SrvVersionAddValidate.class, SrvVersionDetail.SrvVersionUpdateValidate.class})
    private String busiPkgVersion;

    /**
     * 业务包版本编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.busi_pkg_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    @Null(message = "{srvVersions.busiPkgVersionId.notNull}", groups = {SrvVersionDetail.SrvVersionAddValidate.class, SrvVersionDetail.SrvVersionUpdateValidate.class})
    private Integer busiPkgVersionId;

    /**
     * 服务版本构建状态
     */
    private String srvVersionStatus;

    /**
     * 服务版本镜像编号
     */
    private Integer srvImageId;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.create_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.update_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * 创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_version_detail.creator
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.srv_version_id
     *
     * @return the value of acp_srv_version_detail.srv_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public Integer getSrvVersionId() {
        return srvVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.srv_version_id
     *
     * @param srvVersionId the value for acp_srv_version_detail.srv_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setSrvVersionId(Integer srvVersionId) {
        this.srvVersionId = srvVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.srv_id
     *
     * @return the value of acp_srv_version_detail.srv_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public Integer getSrvId() {
        return srvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.srv_id
     *
     * @param srvId the value for acp_srv_version_detail.srv_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setSrvId(Integer srvId) {
        this.srvId = srvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.srv_version
     *
     * @return the value of acp_srv_version_detail.srv_version
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public String getSrvVersion() {
        return srvVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.srv_version
     *
     * @param srvVersion the value for acp_srv_version_detail.srv_version
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setSrvVersion(String srvVersion) {
        this.srvVersion = srvVersion == null ? null : srvVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.srv_version_desc
     *
     * @return the value of acp_srv_version_detail.srv_version_desc
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public String getSrvVersionDesc() {
        return srvVersionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.srv_version_desc
     *
     * @param srvVersionDesc the value for acp_srv_version_detail.srv_version_desc
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setSrvVersionDesc(String srvVersionDesc) {
        this.srvVersionDesc = srvVersionDesc == null ? null : srvVersionDesc.trim();
    }

    public String getBusiPkgVersion() {
        return busiPkgVersion;
    }

    public void setBusiPkgVersion(String busiPkgVersion) {
        this.busiPkgVersion = busiPkgVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.busi_pkg_version_id
     *
     * @return the value of acp_srv_version_detail.busi_pkg_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public Integer getBusiPkgVersionId() {
        return busiPkgVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.busi_pkg_version_id
     *
     * @param busiPkgVersionId the value for acp_srv_version_detail.busi_pkg_version_id
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setBusiPkgVersionId(Integer busiPkgVersionId) {
        this.busiPkgVersionId = busiPkgVersionId;
    }

    public String getSrvVersionStatus() {
        return srvVersionStatus;
    }

    public void setSrvVersionStatus(String srvVersionStatus) {
        this.srvVersionStatus = srvVersionStatus;
    }

    public Integer getSrvImageId() {
        return srvImageId;
    }

    public void setSrvImageId(Integer srvImageId) {
        this.srvImageId = srvImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.create_time
     *
     * @return the value of acp_srv_version_detail.create_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.create_time
     *
     * @param createTime the value for acp_srv_version_detail.create_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.update_time
     *
     * @return the value of acp_srv_version_detail.update_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.update_time
     *
     * @param updateTime the value for acp_srv_version_detail.update_time
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_version_detail.creator
     *
     * @return the value of acp_srv_version_detail.creator
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_version_detail.creator
     *
     * @param creator the value for acp_srv_version_detail.creator
     *
     * @mbggenerated Tue Mar 27 10:30:46 GMT+08:00 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * 镜服务校验分组
     */
    public interface SrvVersionAddValidate {
    }

    public interface SrvVersionUpdateValidate {
    }
}