package com.cloud.paas.taskmanager.entity;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class SrvPersistentRel extends ValueObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    private Integer id;

    /**
     * 服务编号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.srv_id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    private Integer srvId;

    /**
     * 持久化目录
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.persistent_path
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    private String persistentPath;

    /**
     * 持久化目录描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.descr
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private String descr;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.create_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * 更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.update_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * 创建人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acp_srv_persistent_rel.creator
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.id
     *
     * @return the value of acp_srv_persistent_rel.id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.id
     *
     * @param id the value for acp_srv_persistent_rel.id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.srv_id
     *
     * @return the value of acp_srv_persistent_rel.srv_id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public Integer getSrvId() {
        return srvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.srv_id
     *
     * @param srvId the value for acp_srv_persistent_rel.srv_id
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setSrvId(Integer srvId) {
        this.srvId = srvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.persistent_path
     *
     * @return the value of acp_srv_persistent_rel.persistent_path
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public String getPersistentPath() {
        return persistentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.persistent_path
     *
     * @param persistentPath the value for acp_srv_persistent_rel.persistent_path
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setPersistentPath(String persistentPath) {
        this.persistentPath = persistentPath == null ? null : persistentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.descr
     *
     * @return the value of acp_srv_persistent_rel.descr
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.descr
     *
     * @param descr the value for acp_srv_persistent_rel.descr
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.create_time
     *
     * @return the value of acp_srv_persistent_rel.create_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.create_time
     *
     * @param createTime the value for acp_srv_persistent_rel.create_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.update_time
     *
     * @return the value of acp_srv_persistent_rel.update_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.update_time
     *
     * @param updateTime the value for acp_srv_persistent_rel.update_time
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_srv_persistent_rel.creator
     *
     * @return the value of acp_srv_persistent_rel.creator
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_srv_persistent_rel.creator
     *
     * @param creator the value for acp_srv_persistent_rel.creator
     *
     * @mbggenerated Tue Mar 27 10:33:52 GMT+08:00 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}