package com.cloud.paas.taskmanager.model;

import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import java.util.Date;

public class SysConfig extends ValueObject {
    /**
     *配置id
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    @NotNull(message = "{sysconfig.sysconfigid.notnull}",groups = SysConfigUpdate.class)
    private Integer sysConfigId;

    /**
     *配置中文名
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    @NotBlank(message = "{sysconfig.sysconfigchname.notblank}",groups = SysConfigAdd.class)
    private String sysConfigChname;

    /**
     *配置英文名
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    @NotBlank(message = "{sysconfig.sysconfigenname.notblank}",groups = SysConfigAdd.class)
    private String sysConfigEnname;

    /**
     *配置值
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    @NotBlank(message = "{sysconfig.sysconfigvalue.notblank}",groups = SysConfigAdd.class)
    private String sysConfigValue;

    /**
     *配置所属模块
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    @NotBlank(message = "{sysconfig.sysconfigmodule.notblank}",groups = SysConfigAdd.class)
    private String sysConfigModule;

    /**
     *配置描述
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    private String remark;

    /**
     *创建者
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    private String creator;

    /**
     *创建时间
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    private Date createTime;

    /**
     *更新时间
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    private Date updateTime;

    /**
     * 校验
     */
     public interface SysConfigAdd{};
     public interface SysConfigUpdate{};

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.sys_config_id
     *
     * @return the value of acp_sys_config.sys_config_id
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public Integer getSysConfigId() {
        return sysConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.sys_config_id
     *
     * @param sysConfigId the value for acp_sys_config.sys_config_id
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setSysConfigId(Integer sysConfigId) {
        this.sysConfigId = sysConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.sys_config _chname
     *
     * @return the value of acp_sys_config.sys_config _chname
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getSysConfigChname() {
        return sysConfigChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.sys_config _chname
     *
     * @param sysConfigChname the value for acp_sys_config.sys_config _chname
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setSysConfigChname(String sysConfigChname) {
        this.sysConfigChname = sysConfigChname == null ? null : sysConfigChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.sys_config _enname
     *
     * @return the value of acp_sys_config.sys_config _enname
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getSysConfigEnname() {
        return sysConfigEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.sys_config _enname
     *
     * @param sysConfigEnname the value for acp_sys_config.sys_config _enname
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setSysConfigEnname(String sysConfigEnname) {
        this.sysConfigEnname = sysConfigEnname == null ? null : sysConfigEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.sys_config_value
     *
     * @return the value of acp_sys_config.sys_config_value
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getSysConfigValue() {
        return sysConfigValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.sys_config_value
     *
     * @param sysConfigValue the value for acp_sys_config.sys_config_value
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setSysConfigValue(String sysConfigValue) {
        this.sysConfigValue = sysConfigValue == null ? null : sysConfigValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.sys_config_module
     *
     * @return the value of acp_sys_config.sys_config_module
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getSysConfigModule() {
        return sysConfigModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.sys_config_module
     *
     * @param sysConfigModule the value for acp_sys_config.sys_config_module
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setSysConfigModule(String sysConfigModule) {
        this.sysConfigModule = sysConfigModule == null ? null : sysConfigModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.remark
     *
     * @return the value of acp_sys_config.remark
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.remark
     *
     * @param remark the value for acp_sys_config.remark
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.creator
     *
     * @return the value of acp_sys_config.creator
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.creator
     *
     * @param creator the value for acp_sys_config.creator
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.create_time
     *
     * @return the value of acp_sys_config.create_time
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.create_time
     *
     * @param createTime the value for acp_sys_config.create_time
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acp_sys_config.update_time
     *
     * @return the value of acp_sys_config.update_time
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acp_sys_config.update_time
     *
     * @param updateTime the value for acp_sys_config.update_time
     *
     * @mbggenerated Fri Jan 12 10:50:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}